config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'students#index'
  resources :cities
  resources :students do
    collection do
      put :select 
    end
  end
  resources :courses


  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :city
  belongs_to :branch
  has_and_belongs_to_many :courses
  has_attached_file :photo, styles: { small: "64x64", med: "100x100", large: "200x200" }, :default_url => "/assets/:style/1.png"
  validates_attachment :photo, :presence => true, :content_type => { :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] }
    # has_attached_file :photo, :styles => { :original => "922x922>", :thumb => "220x220>" }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
    @courses = Course.all
  end

  def edit
    @student = Student.find(params[:id])
    @courses = Course.all
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      # StudentMailer.welcome(@student).deliver_now
      redirect_to @student
    else
      render 'new'
    end
  end

  def update
    @student = Student.find(params[:id])
    if @student.update!(student_params)
      redirect_to students_path
    else
      render 'edit'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path

  end

private
  def student_params
      params.require(:student).permit(:name, :ernumber, :mobile_no, :student_email, :branch_id, :city_id, :date_of_birth ,:photo, course_ids: [] )
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_editRow.html.erb
<div class = "tr">

<%= form_for @student, remote: true do |form| %>
      <span class="td"><%= form.text_field :name, class: 'form-control', style:"width:150px" %></span>
      <span class="td"><%= form.text_field :ernumber, class: 'form-control', style:"width:150px" %></span>
      <span class="td"><%= form.text_field :mobile_no, class: 'form-control', style:"width:150px" %></span>
      <span class="td"><%= form.text_field :student_email, class: 'form-control', style:"width:150px" %></span>
      <span class="td"><%= form.select :branch_id, options_for_select(Branch.all.collect { |p| [ p.name, p.id ] }), {:prompt => 'Select'}, class: 'form-control', style:"width:150px" %></span>
      <span class="td"><%= form.select :city_id, options_for_select(City.all.collect { |c| [ c.name, c.id ] }), {:prompt => 'Select'}, class: "form-control", style:"width:150px" %></span>
      <span class="td"><%= collection_select(:student, :course_ids, @courses, :id, :name, {}, {:multiple => true, class: "form-control"}) %></span>
      <span class="td"><%= form.text_field :date_of_birth, class: "datepicker form-control input-append date form_datetime", size: "16", style:"width:150px" %></span>
      <span class="td"></span>
      <span class="td"><%= form.file_field :photo, class: 'form-control', style:"width:150px" %></span>
      <span class="td"><%= form.submit "Update", class: 'fa fa-check-square btn btn-primary jsUpdateButton'%></span>
      <span class="td"><button type="button" class=" btn btn-danger btn-sm" data-dismiss="modal">Close</button></span>

  <% end %>
</div>

app/views/students/_form.html.erb
<!-- Modal -->
<div id="new_student_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" class="modal fade" data-backdrop="static">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
    <%= form_with model: @student,id: 'student_form', local: true do |form| %>
      <div class="modal-header">
        <h4 class="modal-title"><i class="fa fa-info-circle">   Student Details</i></h4>
        <button type="button" class="close" data-dismiss="modal">x</button>
      </div>

      <div class="modal-body" style="height: 450px; overflow-y: auto;">
        <div class="form-group">
          <%= form.label :Name, class: 'form-label' %><br>
          <%= form.text_field :name, class: 'form-control form-control-sm', required: 'required' %>
        </div>

        <div class="form-group">
          <%= form.label :Enrollment_Number, class: 'form-label' %><br>
          <%= form.text_field :ernumber, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :mobile_no, class: 'form-label' %><br>
          <%= form.text_field :mobile_no, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :student_email, class: 'form-label' %><br>
          <%= form.text_field :student_email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :branch_id, class: 'form-label' %><br>
          <%= form.select :branch_id, options_for_select(Branch.all.collect { |p| [ p.name, p.id ] }), {:prompt => 'Select'}, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :city_id, class: 'form-label' %><br>
          <%= form.select :city_id, options_for_select(City.all.collect { |c| [ c.name, c.id ] }), {:prompt => 'Select'}, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :course, class: 'form-label' %>
          <%= collection_select(:student, :course_ids, @courses, :id, :name, {}, {:multiple => true, class: "form-control"}) %>
        </div>
        <div class="input-append date form_datetime">
          <%= form.label :date_of_birth, class: 'form-label' %><br>
          <%= form.text_field :date_of_birth, class: "datepicker form-control", size: "16" %>
        </div>

        <div class="form-group">
          <%= form.label :photo, class: 'form-label' %><br>
          <%= form.file_field :photo, class: 'form-control' %>
        </div>
      </div>

      <div class="modal-footer">
        <div class="form-group">
          <%= form.submit "Save Details",style: 'color: white;', class: 'fa fa-floppy-o btn btn-dark'%>
          <button type="button" class=" btn btn-dark btn-sm",style: 'color: white;' data-dismiss="modal">Close</button>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>
</div>

app/views/students/_row.html.erb
<div class="tr" id= "jsRow-<%= student.id %>">

  <span class="td"><%= student.name %></span>
  <span class="td"><%= student.ernumber %></span>
  <span class="td"><%= student.mobile_no %></span>
  <span class="td"><%= student.student_email %></span>
  <span class="td"><%= student.branch.name%></span>
  <span class="td"><%= student.city.name%></span>
  <span class="td"><%= student.courses.map {|c| c.name}.join(', ') %></span>
  <span class="td"><%= student.date_of_birth %></span>
  <span class="td"><%= image_tag  student.photo.url,:size => "50x50" %></span>
  <span class="td"><%= link_to ' ', student_path(student),class: 'btn btn-info fa fa-info-circle', 'data-toggle': 'tooltip', title: 'Show', 'data-placement': 'bottom'%></span>
  <span class="td"><%= link_to ' ', edit_student_path(student), class: 'btn btn-info fa fa-pencil-square-o jsEditButton', 'data-id'=> student.id, remote: true %></span>
  <span class="td"><%= link_to ' ', student_path(student),
        method: :delete,
        data: {confirm: "Are you sure ?"}, class: 'btn btn-info fa fa-trash-o', 'data-toggle': 'tooltip', title: 'Delete', 'data-placement': 'bottom'%></span>

</div>

app/views/students/edit.html.erb
<!-- Modal -->
    <!-- Modal content-->
    <%= form_with model: @student,id: 'student_form',class: 'col-md-6' ,local: true do |form| %>

        <div class="form-group">
          <%= form.label :Name, class: 'form-label' %><br>
          <%= form.text_field :name, class: 'form-control form-control-sm', required: 'required' %>
        </div>

        <div class="form-group">
          <%= form.label :Enrollment_Number, class: 'form-label' %><br>
          <%= form.text_field :ernumber, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :mobile_no, class: 'form-label' %><br>
          <%= form.text_field :mobile_no, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :student_email, class: 'form-label' %><br>
          <%= form.text_field :student_email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :branch_id, class: 'form-label' %><br>
          <%= form.select :branch_id, options_for_select(Branch.all.collect { |p| [ p.name, p.id ] }), {:prompt => 'Select'}, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :city_id, class: 'form-label' %><br>
          <%= form.select :city_id, options_for_select(City.all.collect { |c| [ c.name, c.id ] }), {:prompt => 'Select'}, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :course, class: 'form-label' %>
          <%= collection_select(:student, :course_ids, @courses, :id, :name, {}, {:multiple => true, class: "form-control"}) %>
        </div>
        <div class="input-append date form_datetime">
          <%= form.label :date_of_birth, class: 'form-label' %><br>
          <%= form.text_field :date_of_birth, class: "datepicker form-control", size: "16" %>
        </div>

        <div class="form-group">
          <%= form.label :photo, class: 'form-label' %><br>
          <%= form.file_field :photo, class: 'form-control' %>
        </div>
      </div>

        <div class="form-group">
          <%= form.submit "Save Details",style: 'color: white;', class: 'fa fa-floppy-o btn btn-dark'%>
          <button type="button" class=" btn btn-dark btn-sm",style: 'color: white;' data-dismiss="modal">Close</button>
      </div>
    <% end %>

app/views/students/edit.js.erb
// $('#popup_modal').html("<%= j render 'form' %>");
// $('#new_student_modal').modal();
  // $('#jsRow-' + $(this).data('id')).empty().append('111111111111111');
  // $("#jsRow-"+"<%#= @student.id %>").empty().append('1111111111');

  // $("#jsEditRow-"+"<%#= @student.id %>").hide();
  $("#jsRow-"+"<%= @student.id %>").html("<%= j render partial: 'editRow' %>");
  

app/views/students/index.html.erb
<style>
  DIV.table table-bordered
  {
      display:table;
  }
  FORM.tr, DIV.tr, DIV.th
  {
      display:table-row;
  }
  SPAN.td
  {
      display:table-cell;
      width: 150px;
  }
  DIV.tbody
  {
      display: table;
  }
</style>

<div style="margin: 10px;">
  <h1><i class="fa fa-graduation-cap" aria-hidden="true"> Students Details List</i></h1>
  <%= link_to '', new_student_path(@student), class: 'btn btn-info fa fa-plus-circle', 'data-toggle': 'tooltip', title: 'New', 'data-placement': 'bottom', remote: true %>
<br/><br/>
</div>
<div class = "table table-bordered" id = "tablecontent">
  <div class = "tr">
    <span class="td" style= "text-align: center;">Name</span>
    <span class="td" style= "text-align: center;">Enrollment Number</span>
    <span class="td" style= "text-align: center;">Mobile Number</span>
    <span class="td" style= "text-align: center;">Student Email</span>
    <span class="td" style= "text-align: center;">Branch</span>
    <span class="td" style= "text-align: center;">City</span>
    <span class="td" style= "text-align: center;">Course</span>
    <span class="td" style= "text-align: center;">Date of Birth</span>
    <span class="td" style= "text-align: center;">Profile Image</span>
    <span class="td" style= "text-align: center;">Action</span>
  </div>
  <div class="tbody">
    <% @students.each do |student| %>
      <%= render partial: 'row', locals: {student: student} %>
    <% end %>
  </div><br>
</div>

app/views/students/new.html.erb
  <!-- <h1><i class="fa fa-plus-square" aria-hidden="true"> Students Details!</i></h1> -->
  <%= render 'form' %>

app/views/students/new.js.erb
$('#popup_modal').html("<%= j render 'form' %>");
$('#new_student_modal').modal();
$('#student_form').validate();

app/views/students/show.html.erb
<div style="margin:15px;" >

<h1><i class="fa fa-graduation-cap" aria-hidden="true"> Students Details!</i></h1>
<table class="col-md-6 table table-striped table-bordered">
  <thead>
    <th><strong>Name :</strong></th>
    <th><%= @student.name%></th>
</thead>

<tbody>
  <tr>
    <td><strong>Enrollment_Number :</strong></td>
    <td><%= @student.ernumber%></td>
  </tr>


  <tr>
    <td><strong>Mobile_No :</strong></td>
    <td><%= @student.mobile_no%></td>
  </tr>

  <tr>
    <td><strong>student_email :</strong></td>
    <td><%= @student.student_email%></td>
  </tr>

  <tr>
    <td><strong>Branch :</strong></td>
    <td><%= @student.branch.name%></td>
  </tr>

  <tr>
    <td><strong>City :</strong></td>
    <td><%= @student.city.name%></td>
  </tr>
  <tr>
    <td><strong>Course Name:</strong></td>
    <td><%= @student.courses.map {|c| c.name}.join(', ') %></td>
  </tr>
  <tr>
    <td><strong>Date Of Birth:</strong></td>
    <td><%= @student.date_of_birth %></td>
  </tr>
  <tr>
      <td><strong>Student Profile Image :</strong></td>
      <td><%= image_tag @student.photo.url, size: "50x50"%></td>
  </tr>
</tbody>
</table>

<%= link_to ' Back', students_path,style: 'color: white;', class:'fa fa-arrow-left btn btn-dark'%>
<%= link_to ' Edit', edit_student_path(@student), style: 'color: white;', class: 'fa fa-pencil-square-o btn btn-dark', remote: true  %>


</div>

app/views/students/show.js.erb
$('#popup_modal').html("<%= j render 'show' %>");
$('#new_student_modal').modal();