config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'students#index'
  resources :cities
  resources :students do
    collection do
      put :select 
    end
  end
  resources :courses


  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  has_many :students
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
    @students = Student.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def edit
    @course = Course.find(params[:id])
    @students = Student.all

  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to @course
    else
      render 'new'
    end
  end



  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to @course
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to course_path
  end



  private
    def course_params
        params.require(:course).permit(:name, :student_ids => [])
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.erb
<br><h1>Add Your Course</h1><hr><br>
<%= form_for @course do |form| %>
<div class="col-md-4 form-group">
  <%= form.label :name, class: 'form-label' %><br>
  <%= form.text_field :name, class: 'form-control form-control-sm' %><br>
  <div class="form-group">
    <%= collection_select(:course, :student_ids, @students, :id, :name, {}, {:multiple => true, class: "form-control"}) %>
  </div>
  <%= form.submit "Save Details",style: 'color: white;', class: 'fa fa-floppy-o btn btn-dark'%>
  <%= link_to 'Back', courses_path, style: 'color: white;', class: 'fa fa-arrow-left btn btn-dark' %>

<% end %>

app/views/courses/index.html.erb
<div style="margin: 10px;">
  <h1>Course Details List</h1>
  <%= link_to ' New', new_course_path(@course), class: 'btn btn-info fa fa-plus-circle' %>

  <%#= link_to 'New', new_student_path(@student),{:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#popup_modal', class: 'btn btn-info fa fa-plus-square-o'} %><br><br>
</div>
<table class="table table-striped text-center col-md-6">
  <tr>
    <th>Course</th>
    <th>Student</th>
    <th  colspan="3">Action</th>
  </tr>

    <% @courses.each do |course| %>
    <tr>
      <td><%= course.name %></td>
      <td><%= course.students.map {|s| s.name}.join('') %></td>
      <td><%= link_to ' Show', course_path(course),class: 'btn btn-info fa fa-info-circle' %></td>
      <td><%= link_to ' Edit', edit_course_path(course),class: 'btn btn-info fa fa-pencil-square-o' %></td>
      <td><%= link_to ' delete', course_path(course),
            method: :delete,
            data: {confirm: "Are you sure ?"}, class: 'btn btn-info fa fa-trash-o'%></td>
    </tr>
    <% end %>

</table>

app/views/courses/new.html.erb
<br><h1>Add Your Course</h1><hr><br>
<%= form_for @course do |form| %>
<div class="col-md-4 form-group">
  <%= form.label :name, class: 'form-label' %><br>
  <%= form.text_field :name, class: 'form-control form-control-sm' %><br>
  <div class="form-group">
    <%= collection_select(:course, :student_ids, @students, :id, :name, {}, {:multiple => true, class: "form-control"}) %>

    <%#= collection_check_boxes(:course, :student_ids, @students, :id, :name) %>
  </div>
  <%= form.submit "Save Details",style: 'color: white;', class: 'fa fa-floppy-o btn btn-dark'%>
  <%= link_to 'Back', courses_path, style: 'color: white;', class: 'fa fa-arrow-left btn btn-dark' %>

<% end %>

app/views/courses/show.html.erb
<div style="margin:15px;" >

  <br><h1>Courses Details</h1>
  <table class="col-md-6 table table-striped table-bordered">
    <tr>
      <td><strong>Name </strong></td>
      <td><%= @course.name%></td>
    </tr>
    <tr>
    	<td><strong>Student Name:</strong></td>
    	<td><%= @course.students.map {|s| s.name}.join('') %></td>
    </tr>
  </table>
  <%= link_to 'Back', courses_path,style: 'color: white;', class:'fa fa-arrow-left btn btn-dark'%>
  <%= link_to ' Edit', edit_course_path(@course), style: 'color: white;', class: 'fa fa-pencil-square-o btn btn-dark' %>

</div>