config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'students#index'
  resources :cities
  resources :students do
    collection do
      put :select 
    end
  end
  resources :courses


  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  has_many :students
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def new
     @city = City.new
  end

  def show
    @students = Student.where(city_id: params[:id])
  end

  def edit
      @city = City.find(params[:id])
  end

  def create
    @city = City.create(cities_params)
    if @city.save
      redirect_to @city
    else
      rende 'new'
    end
  end

  def update
    @city = City.find(params[:id])
    if @city.update(cities_params)
      redirect_to @city
    else
      render 'edit'
    end
  end 

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_to city_path
  end


private
  def cities_params
    params.require(:city).permit(:name)

  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for @city do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br><hr>
  <%= f.submit %>
<%end %> 

app/views/cities/edit.html.erb
<h1>Edit Cities Details</h1>
<%= render 'form' %>
<%= link_to 'Back', city_path %>

app/views/cities/index.html.erb
<h1>Cities Details</h1>
<table>
  <tr>
    <th>City</th>
    <th></th>
  </tr>

    <% @cities.each do |city| %>
    <tr>
      <td><%= city.name %></td>
      <td><%= link_to 'Show', city_path(city) %></td>
      <td><%= link_to 'Edit', edit_city_path(city) %></td>
      <td><%= link_to 'delete', city_path(city),
            method: :delete,
            data: {confirm: "Are you sure ?"}%></td>
    </tr>
    <% end %>

</table>

app/views/cities/new.html.erb
<h1>Add Your City</h1><hr><br>
<%= render 'form' %>

app/views/cities/show.html.erb
<h1>Students name</h1><hr>
<% @students.each do |student|  %>
 <%= student.name %><br>
<% end %>